[build-system]
requires = [
    "setuptools>=59.5.0",
    "wheel",
]

[tool.black]
target-version = ['py39', 'py310']
exclude = '''
(
    asv_bench/env
  | \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)
'''
